### ISSUE TITLE
Address various UI issues

### ISSUE THREAD

**Issue by dckesler** [celo-org/web-core#2]

**Comment by dckesler** [comment]
- [ ] Unsupported base contract warning
- [ ] When accepting cookies there is a checkbox for "Updates (Beamer)" that needs to be removed
- [ ] Favicon needs to be changed

**Comment by nicolasbrugneaux** [comment]
- [x] cookies
- [x] favicons


still investigating the unsupported base contract warning

**Comment by nicolasbrugneaux** [comment]
Unsupported base contract was coming from a wrongly set env variable on the tx service. Redeploying them should fix it.

**Comment by nicolasbrugneaux** [comment]
Deployed
