### ISSUE TITLE
Bug: Transaction error relating to not showing gas estimate

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/web-core#4]
_Copying a [question](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/31?u=0xarthurxyz) from the Celo Safe forum post for tracking purposes: [[Multisig] Celo Safe (re)launch](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529)_

> Report: Tx not showing estimate
> 
> STEPS
> 
> Try to confirm a tx
> tx modal to confirm pops up
> “Estimating…” text on bottom right button
> Result
> 4. not getting an estimate with error in the modal [1]
> (5. follow-up issue: when I still “Confirm” the tx
> 6. Then error message pops up in the upper right corner [2])
> 
> Expected
> 4. Get an estimate
> 
> [1]
> Happened for 3 days already
> (can’t post screenshots :frowning: )
> 
> > This transaction will most likely fail. To save gas costs, avoid creating the transaction.call revert exception [ See: [Error Codes](https://links.ethers.org/v5-errors-CALL_EXCEPTION) ] (method=“getGasPriceMinimum(address)”, data=“0x”, errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
> 
> [2]
> 
> > Your transaction was unsuccessful. cannot estimate gas; transaction may fail or may require manual gas limit [ See: [Error Codes](https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT) ] (reason=“execution reverted: GS013”, method=“estimateGas”, transaction={“from”:“0xB86fa0cfEEA21558DF988AD0ae22F92a8EF69AC1”,“to”:"0xF1734d53F5560C319395D633D1

**Comment by tamagosante** [comment]
> "can't post screenhots"

 On gh can:

![image](https://user-images.githubusercontent.com/30693990/202266521-05ec6ff3-2a88-49b7-9e40-271b2bebb0d4.png)

**Comment by martinvol** [comment]
Hello @hiaux0

I was able to reproduce the error in the alfajores deployment but not on the mainnet version, did you encounter any issues with the mainnet version as well?

**Comment by tamagosante** [comment]
@martinvol 

> mainnet

I don't encounter that issue on Celo mainnet (just tested).

I just tried for Alfajores again, and it seemed to work.
While I _do_ get the "likely fail" message, I did not get the top right pop-up.
I was able to send a small amount to myself with no hiccups

**Comment by martinvol** [comment]
I suspect this is a rate limit error in our alfajores instance, let me check

**Comment by arthurgousset** [comment]
Closing this because I expect the issue is resolved. Feel free to re-open the ticket if that's not the case.
